# OAuth credential for the Twitter API
consumer_key: PUT_YOUR_API_KEY_DATA_HERE
consumer_secret: PUT_YOUR_API_KEY_DATA_HERE
oauth_token: PUT_YOUR_API_KEY_DATA_HERE
oauth_secret: PUT_YOUR_API_KEY_DATA_HERE

# URL of the Twitter API for the keyword search stream
url_filter: https://stream.twitter.com/1.1/statuses/filter.json

# URL of the Twitter API for the user timeline
url_user: https://api.twitter.com/1.1/statuses/user_timeline.json

# number of tweets to download in one batch
count: 200

# waiting time between batches
wait: 30
